import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Incident } from "@/data/safetyData";

interface ReportInput {
  incidents: Incident[];
  injectedCount: number;
}

export function generateSafetyReport({ incidents, injectedCount }: ReportInput) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const now = new Date();
  const dateStr = now.toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });

  const active = incidents.filter((i) => !i.resolved);
  const resolved = incidents.filter((i) => i.resolved);
  const critical = active.filter((i) => i.severity === "critical").length;
  const aiDetectionsToday = 71 + injectedCount;

  // ===== Header band =====
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 80, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Warehouse Safety Intelligence", 40, 38);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text("Demo Session Report  -  AI-Powered Vision Analytics", 40, 56);
  doc.text(dateStr, pageWidth - 40, 56, { align: "right" });

  // ===== Summary section =====
  let y = 110;
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Session Summary", 40, y);
  y += 8;
  doc.setDrawColor(226, 232, 240);
  doc.line(40, y, pageWidth - 40, y);
  y += 18;

  const stats: [string, string][] = [
    ["Scenarios Triggered (this session)", String(injectedCount)],
    ["AI Detections Today", String(aiDetectionsToday)],
    ["Active Incidents", String(active.length)],
    ["Critical Incidents", String(critical)],
    ["Resolved Incidents", String(resolved.length)],
    ["Total Incidents on Record", String(incidents.length)],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: stats,
    theme: "grid",
    headStyles: { fillColor: [30, 41, 59], textColor: 255, fontSize: 10 },
    bodyStyles: { fontSize: 10, textColor: [30, 41, 59] },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } },
    margin: { left: 40, right: 40 },
  });

  // ===== Active incidents =====
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let cursorY = (doc as any).lastAutoTable.finalY + 28;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text("Active Incidents", 40, cursorY);
  cursorY += 8;
  doc.line(40, cursorY, pageWidth - 40, cursorY);
  cursorY += 6;

  if (active.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text("No active incidents at time of report.", 40, cursorY + 16);
    cursorY += 30;
  } else {
    autoTable(doc, {
      startY: cursorY + 6,
      head: [["ID", "Type", "Zone", "Severity", "AI Conf.", "When"]],
      body: active.map((i) => [
        i.id,
        i.type,
        i.zone,
        i.severity.toUpperCase(),
        `${i.aiConfidence}%`,
        i.timestamp,
      ]),
      theme: "striped",
      headStyles: { fillColor: [220, 38, 38], textColor: 255, fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      margin: { left: 40, right: 40 },
    });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    cursorY = (doc as any).lastAutoTable.finalY + 28;
  }

  // ===== Resolved incidents =====
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text("Resolved Incidents", 40, cursorY);
  cursorY += 8;
  doc.line(40, cursorY, pageWidth - 40, cursorY);

  if (resolved.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text("No resolved incidents.", 40, cursorY + 22);
  } else {
    autoTable(doc, {
      startY: cursorY + 6,
      head: [["ID", "Type", "Zone", "Severity", "AI Conf.", "When"]],
      body: resolved.map((i) => [
        i.id,
        i.type,
        i.zone,
        i.severity.toUpperCase(),
        `${i.aiConfidence}%`,
        i.timestamp,
      ]),
      theme: "striped",
      headStyles: { fillColor: [34, 197, 94], textColor: 255, fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      margin: { left: 40, right: 40 },
    });
  }

  // ===== Footer on every page =====
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      "Generated by Warehouse Safety Intelligence  -  Confidential",
      40,
      doc.internal.pageSize.getHeight() - 20
    );
    doc.text(
      `Page ${p} of ${pageCount}`,
      pageWidth - 40,
      doc.internal.pageSize.getHeight() - 20,
      { align: "right" }
    );
  }

  const filename = `safety-report-${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
  return filename;
}
